---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  namespace: echoserver
  labels:
    backstage.io/kubernetes-id: homelab-bootstrap-k3s
spec:
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
